export const NAMES = [
  { firstName: "Basil", lastName: "Fawlty" },
  { firstName: "Del", lastName: "Trotter" },
  { firstName: "Hyacinth", lastName: "Bucket" },
  { firstName: "Edmund", lastName: "Blackadder" },
  { firstName: "David", lastName: "Brent" },
  { firstName: "Arthur", lastName: "Daley" },
  { firstName: "Victor", lastName: "Meldrew" },
  { firstName: "Sherlock", lastName: "Holmes" },
  { firstName: "John", lastName: "Watson" },
  { firstName: "Jean-Luc", lastName: "Picard" },
  { firstName: "Tommy", lastName: "Shelby" },
  { firstName: "James", lastName: "Moriarty" },
  { firstName: "Rodney", lastName: "Trotter" },
  { firstName: "Patsy", lastName: "Stone" },
  { firstName: "Edina", lastName: "Monsoon" },
  { firstName: "Mark", lastName: "Corrigan" },
  { firstName: "Jeremy", lastName: "Usborne" },
  { firstName: "Graham", lastName: "Chapman" },
  { firstName: "Eric", lastName: "Idle" },
  { firstName: "John", lastName: "Cleese" },
  { firstName: "Michael", lastName: "Palin" },
  { firstName: "Terry", lastName: "Jones" },
  { firstName: "Terry", lastName: "Gilliam" },
];
